apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homero-app
  namespace: argocd
spec:
  destination:
    namespace: homero-app
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: "."
    repoURL: "git@ssh.dev.azure.com:v3/lds-ifce/DevOps/k8s"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true